#
###################################
# Site wide configuration
####################################
#
title: Hektowin
email: getintouch@hekto.win
description: Kalite için kreatif içerikler
url: 
keywords: ["Programlama", "Online Pazarlama", "Online Yayıncılık"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Istanbul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Hektowin
  avatar: 
  job: "Bilinmeyenler • Merak Edilenler • İlginç İçerikler"
  bio: "getintouch@hekto.win"
  email: 
  disqus-shortname: hekto-win
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-114360182-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: hekto.win
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
  
