#
###################################
# Site wide configuration
####################################
#
title: Mutecute.site
email: mutecutespace@gmail.com
description: A simple and awesome blog theme powered by jekyll.
url: https://bearpear.github.io/mutecute.github.io # the base hostname & protocol for your site
keywords: ["Programlama", "Online Pazarlama", "Online Yayıncılık"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Istanbul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Mutecute.site
  avatar: leonids-logo.png
  job: "Programlama • Online Pazarlama • Online Yayıncılık"
  bio: "A backend developer who loves design awesome things. Working for RendezvousCheznous atm in Marseille, France."
  email: mutecutespace@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: renyuanz #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: renyuan-zou-69b7038a #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
